/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/snapshot": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil snapshot kondisi dunia kantor saat ini
         * @description Mengembalikan kondisi dunia kantor saat ini (WorldSnapshot), mencakup seluruh status
         *     agen (16 agen), linimasa aktivitas terkini (hingga 500 event dari ring buffer), status
         *     event kolektif yang sedang aktif, dan telemetri sumber daya host.
         *     Secara default mengembalikan proyeksi publik (projection=public) yang telah diredaksi
         *     secara ketat. Jika projection=founder diminta, request wajib menyertakan cookie sesi
         *     Founder yang valid.
         */
        get: operations["getWorldSnapshot"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/stream": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Stream Server-Sent Events (SSE) real-time
         * @description Membuka koneksi satu arah Server-Sent Events (SSE) persisten dari server ke browser.
         *     Saat pertama kali terhubung, server mengirimkan event snapshot lengkap.
         *     Selanjutnya, server menyiarkan delta pembaruan status agen (agent), event linimasa baru (event),
         *     telemetri host periodik (vitals), dan status event kolektif (collective).
         *     Komentar keep-alive (: ping\n\n) dikirimkan setiap 15 detik.
         *     Klien dapat melakukan resume koneksi yang terputus dengan menyertakan header Last-Event-ID.
         */
        get: operations["streamEvents"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/agents/{id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Ambil profil dan status detail satu agen
         * @description Mengembalikan profil lengkap agen tertentu, status kerja saat ini, dan 5 riwayat task
         *     terakhir yang dikerjakan. Pada proyeksi publik, judul task disamarkan berdasarkan peran agen
         *     dan field teks internal ditiadakan.
         */
        get: operations["getAgentDetail"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Login Founder
         * @description Mengautentikasi Founder menggunakan verifikasi hash Argon2. Jika kredensial valid,
         *     server mengembalikan cookie sesi office_session dengan atribut HttpOnly, Secure,
         *     dan SameSite=Strict.
         *     Wajib menyertakan header X-Office-Intent: 1 sebagai perlindungan mitigasi CSRF.
         *     Dibatasi maksimal 5 percobaan per 15 menit per alamat IP.
         */
        post: operations["loginFounder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Logout Founder
         * @description Menghapus cookie sesi Founder dan mengakhiri sesi administratif.
         *     Wajib menyertakan header X-Office-Intent: 1.
         */
        post: operations["logoutFounder"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/collective": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /**
         * Picu event kolektif kantor (Founder)
         * @description Memicu event kolektif manual di kantor (Rapat Mendadak, Break Time, atau Sholat Berjamaah).
         *     Hanya dapat dipanggil oleh Founder yang telah terautentikasi dan wajib membawa header
         *     X-Office-Intent: 1. Event disimpan di memori state engine dengan durasi TTL tertentu,
         *     lalu otomatis berakhir. Task nyata agen tetap memiliki prioritas tertinggi.
         */
        post: operations["triggerCollectiveEvent"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/healthz": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Health check dan status konektivitas reader
         * @description Memeriksa kesiapan layanan backend FastAPI, uptime proses, konsumsi memori RSS Uvicorn,
         *     dan kesehatan konektivitas ke seluruh sumber data Hermes (kanban, gateway, profiles, host).
         */
        get: operations["getHealthStatus"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** @description Kondisi operasional dan visual seorang agen di kantor virtual. */
        AgentState: {
            /**
             * @description Identifier unik agen.
             * @example forge
             * @enum {string}
             */
            id: "jarvis" | "daedalus" | "oracle" | "forge" | "prism" | "sentinel" | "muse" | "bastion" | "relay" | "vector" | "nova" | "steward" | "scribe" | "merlin" | "warden" | "rifqi";
            /**
             * @description Nama tampilan agen.
             * @example Forge
             */
            name: string;
            /**
             * @description Peran atau spesialisasi rekayasa agen.
             * @example Backend Specialist
             */
            role: string;
            /**
             * @description Status kehadiran agen di kantor.
             * @example on_duty
             * @enum {string}
             */
            presence: "on_duty" | "off_duty";
            /**
             * @description Status eksekusi kerja agen yang menentukan animasi dan penanda visual.
             * @example working
             * @enum {string}
             */
            work: "idle" | "working" | "blocked" | "stale" | "failed" | "done_recent" | "off_duty";
            /**
             * @description Unix timestamp detik saat status kerja saat ini dimulai.
             * @example 1791028303
             */
            since: number;
            /**
             * @description Jumlah tugas yang berhasil diselesaikan hari ini (sejak 00:00:00 Asia/Jakarta).
             * @example 4
             */
            done_today: number;
            /**
             * @description Zona ruangan tempat agen saat ini berada.
             * @example backend_den
             */
            zone: string;
            /**
             * @description Deskripsi aksi visual mikro agen saat ini.
             * @example Menulis kode endpoint database
             */
            action: string;
            /**
             * @description Koordinat kolom grid isometrik (0-43).
             * @example 18
             */
            grid_x?: number;
            /**
             * @description Koordinat baris grid isometrik (0-31).
             * @example 12
             */
            grid_y?: number;
            /**
             * @description Orientasi hadap karakter.
             * @example SE
             * @enum {string}
             */
            direction?: "SE" | "NE" | "SW" | "NW";
            task?: components["schemas"]["TaskRef"] | null;
        };
        /**
         * @description Referensi tugas Kanban yang sedang atau baru saja dikerjakan agen.
         *     Pada proyeksi publik, judul disamarkan dan field internal bernilai null.
         *     Pada proyeksi founder, seluruh atribut ditampilkan (teks dipotong maks 500 karakter).
         */
        TaskRef: {
            /**
             * @description Identifier unik tugas Kanban.
             * @example t_f857a584
             */
            id: string;
            /**
             * @description Judul tugas (tersanitasi/disamarkan pada publik, asli pada founder).
             * @example Pengembangan modul backend dan database
             */
            title: string;
            /**
             * @description Nama board Kanban (nama asli jika allowlisted, atau Proyek internal).
             * @example office-v2
             */
            board: string;
            /**
             * @description Status tugas di Kanban.
             * @example running
             * @enum {string}
             */
            status: "todo" | "ready" | "running" | "blocked" | "done" | "failed";
            /**
             * @description Alasan pemblokiran tugas jika berstatus blocked.
             * @example null
             * @enum {string|null}
             */
            block_kind?: "needs_input" | "dependency" | "capability" | "transient" | null;
            /**
             * @description Unix timestamp detik saat tugas mulai dijalankan.
             * @example 1791027159
             */
            started_at?: number | null;
            /**
             * @description Deskripsi lengkap tugas (hanya muncul di proyeksi Founder, dipotong maks. 500 karakter).
             * @example null
             */
            body?: string | null;
            /**
             * @description Ringkasan hasil eksekusi tugas (hanya muncul di proyeksi Founder).
             * @example null
             */
            summary?: string | null;
            /**
             * @description Hasil eksekusi singkat (hanya muncul di proyeksi Founder).
             * @example null
             */
            result?: string | null;
            /**
             * @description Pesan kegagalan atau error run (hanya muncul di proyeksi Founder).
             * @example null
             */
            error?: string | null;
            /**
             * @description Path absolut workspace run di server (hanya muncul di proyeksi Founder).
             * @example null
             */
            workspace_path?: string | null;
            /**
             * @description Nama branch git pengerjaan tugas (hanya muncul di proyeksi Founder).
             * @example null
             */
            branch_name?: string | null;
            /**
             * @description Process ID worker agent di OS Linux (hanya muncul di proyeksi Founder).
             * @example null
             */
            worker_pid?: number | null;
        };
        /** @description Representasi peristiwa atau aktivitas di kantor virtual untuk umpan linimasa (feed). */
        OfficeEvent: {
            /**
             * @description Nomor urut sequence global yang monoton bertambah, digunakan untuk resume SSE.
             * @example 142
             */
            seq: number;
            /**
             * @description Unix timestamp detik terjadinya peristiwa.
             * @example 1791028303
             */
            ts: number;
            /**
             * @description Board sumber peristiwa (nama asli jika allowlisted, atau Proyek internal).
             * @example office-v2
             */
            board: string;
            /**
             * @description Jenis peristiwa kantor.
             * @example task_started
             * @enum {string}
             */
            kind: "task_created" | "task_started" | "task_commented" | "task_blocked" | "task_done" | "task_failed" | "task_stale" | "agent_online" | "agent_offline" | "collective_started" | "collective_ended" | "vitals_alert";
            /**
             * @description ID agen yang terdampak atau menjadi pelaku utama.
             * @example forge
             */
            agent?: string | null;
            /**
             * @description ID agen aktor yang memicu aksi (misal penulis komentar).
             * @example jarvis
             */
            actor?: string | null;
            /**
             * @description Pesan ramah pengguna yang ditampilkan pada linimasa feed.
             * @example Forge mulai mengerjakan tugas pengembangan modul backend
             */
            message: string;
            task?: components["schemas"]["TaskRef"] | null;
        };
        /** @description Snapshot menyeluruh kondisi dunia kantor pada suatu waktu. */
        WorldSnapshot: {
            /**
             * @description Unix timestamp detik saat snapshot ini digenerate oleh server.
             * @example 1791028310
             */
            generated_at: number;
            /**
             * @description Nomor sequence event terakhir yang tercakup dalam snapshot ini.
             * @example 142
             */
            seq: number;
            /**
             * @description Tingkat proyeksi data dari snapshot ini.
             * @example public
             * @enum {string}
             */
            projection: "public" | "founder";
            /**
             * @description Waktu pencahayaan atmosfer saat ini berdasarkan jam lokal Asia/Jakarta (WIB).
             * @example day
             * @enum {string}
             */
            time_of_day: "dawn" | "day" | "dusk" | "night";
            /** @description Daftar kondisi terkini dari seluruh 16 agen kantor. */
            agents: components["schemas"]["AgentState"][];
            /** @description Daftar hingga 500 peristiwa kantor terbaru dari ring buffer di memori. */
            recent_events: components["schemas"]["OfficeEvent"][];
            active_collective?: components["schemas"]["CollectiveEventState"] | null;
            vitals: components["schemas"]["HostVitals"];
        };
        /** @description Kondisi event interaksi kolektif yang melibatkan banyak agen. */
        CollectiveEventState: {
            /**
             * @description Identifier unik instans event kolektif.
             * @example coll_98f12a
             */
            id: string;
            /**
             * @description Jenis aktivitas kolektif.
             * @example rapat
             * @enum {string}
             */
            kind: "rapat" | "break" | "sholat";
            /**
             * @description Judul atau tema event kolektif.
             * @example Rapat Koordinasi Arsitektur
             */
            title: string;
            /**
             * @description Unix timestamp detik saat event dimulai.
             * @example 1791028000
             */
            started_at: number;
            /**
             * @description Unix timestamp detik saat event akan kedaluwarsa secara otomatis.
             * @example 1791028300
             */
            expires_at: number;
            /**
             * @description Daftar ID agen yang mengikuti event kolektif ini.
             * @example [
             *       "jarvis",
             *       "daedalus",
             *       "forge",
             *       "prism"
             *     ]
             */
            participants: string[];
            /**
             * @description Menandakan apakah event masih aktif berlangsung.
             * @example true
             */
            active: boolean;
        };
        /** @description Metrik sumber daya server VPS tempat sistem beroperasi. */
        HostVitals: {
            /**
             * Format: float
             * @description Persentase penggunaan CPU (dibulatkan ke bilangan bulat pada mode publik).
             * @example 14
             */
            cpu_percent: number;
            /**
             * Format: float
             * @description Persentase penggunaan memori RAM (dibulatkan ke bilangan bulat pada mode publik).
             * @example 38
             */
            memory_percent: number;
            /**
             * Format: float
             * @description Persentase penggunaan partisi penyimpanan disk (dibulatkan pada mode publik).
             * @example 62
             */
            disk_percent: number;
            /**
             * @description Status umum kesehatan infrastruktur host.
             * @example healthy
             * @enum {string}
             */
            status: "healthy" | "warning" | "critical";
            details?: components["schemas"]["HostVitalsDetails"] | null;
        };
        /** @description Rincian telemetri perangkat keras dan proses server (hanya tersedia di proyeksi Founder). */
        HostVitalsDetails: {
            /**
             * @description Jumlah core CPU fisik/virtual host.
             * @example 8
             */
            cpu_cores: number;
            /**
             * Format: float
             * @description Load average server 1 menit terakhir.
             * @example 0.85
             */
            load_1m: number;
            /**
             * Format: float
             * @description Load average server 5 menit terakhir.
             * @example 0.92
             */
            load_5m: number;
            /**
             * Format: float
             * @description Load average server 15 menit terakhir.
             * @example 0.78
             */
            load_15m: number;
            /**
             * Format: float
             * @description Total kapasitas RAM fisik dalam megabyte.
             * @example 16384
             */
            memory_total_mb: number;
            /**
             * Format: float
             * @description Penggunaan RAM aktif saat ini dalam megabyte.
             * @example 6225
             */
            memory_used_mb: number;
            /**
             * Format: float
             * @description Sisa RAM yang tersedia dalam megabyte.
             * @example 10159
             */
            memory_available_mb: number;
            /**
             * Format: float
             * @description Total kapasitas penyimpanan root disk dalam gigabyte.
             * @example 120
             */
            disk_total_gb: number;
            /**
             * Format: float
             * @description Penggunaan ruang disk saat ini dalam gigabyte.
             * @example 74.4
             */
            disk_used_gb: number;
            /**
             * Format: float
             * @description Total waktu aktif server host sejak boot dalam detik.
             * @example 864200
             */
            uptime_seconds: number;
        };
        /** @description Informasi profil mendalam seorang agen beserta riwayat tugas terakhir. */
        AgentProfileDetail: {
            agent: components["schemas"]["AgentState"];
            bio: components["schemas"]["AgentBio"];
            /** @description Daftar 5 tugas terakhir yang dikerjakan oleh agen (disanitasi per proyeksi). */
            recent_tasks: components["schemas"]["TaskRef"][];
        };
        /** @description Data profil persona, peran, dan preferensi kerja seorang agen. */
        AgentBio: {
            /** @example forge */
            id: string;
            /** @example Forge */
            name: string;
            /** @example The Blacksmith */
            alias?: string | null;
            /** @example Backend Specialist */
            role: string;
            /** @example Core Engineering */
            department: string;
            /** @example Pekerja keras, teliti, pragmatis, sangat menyukai optimasi database */
            personality: string;
            /**
             * @example [
             *       "Python",
             *       "FastAPI",
             *       "SQLite WAL",
             *       "AsyncIO"
             *     ]
             */
            specialties: string[];
            /** @example #3B82F6 */
            primary_color: string;
            /** @example backend_den */
            desk_zone: string;
        };
        /** @description Kredensial autentikasi Founder. */
        LoginRequest: {
            /**
             * Format: password
             * @description Kata sandi Founder.
             * @example SuperSecretFounderPassphrase2026!
             */
            password: string;
        };
        /** @description Respons keberhasilan autentikasi Founder. */
        LoginResponse: {
            /** @example true */
            success: boolean;
            /** @example founder */
            role: string;
            /**
             * @description Unix timestamp detik berakhirnya masa aktif sesi.
             * @example 1791633103
             */
            expires_at: number;
        };
        /** @description Respons pengakhiran sesi Founder. */
        LogoutResponse: {
            /** @example true */
            success: boolean;
        };
        /** @description Parameter untuk memicu event interaksi kolektif. */
        TriggerCollectiveRequest: {
            /**
             * @description Jenis event yang ingin dipicu.
             * @example rapat
             * @enum {string}
             */
            kind: "rapat" | "break" | "sholat";
            /**
             * @description Durasi berlangsungnya event dalam detik (default 300 detik / 5 menit).
             * @default 300
             * @example 300
             */
            duration_seconds: number;
            /**
             * @description Daftar ID agen yang diundang. Jika kosong, mengikutsertakan seluruh agen idle.
             * @example [
             *       "jarvis",
             *       "daedalus",
             *       "forge",
             *       "prism"
             *     ]
             */
            participants?: string[];
            /**
             * @description Judul kustom untuk event kolektif.
             * @example Rapat Koordinasi Arsitektur
             */
            title?: string;
        };
        /** @description Kondisi kesehatan modul pembaca data sumber. */
        ReaderHealth: {
            /**
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /**
             * @description Unix timestamp detik pembacaan terakhir.
             * @example 1791028303
             */
            last_poll: number;
            /**
             * @description Pesan error terakhir jika status error atau degraded.
             * @example null
             */
            error?: string | null;
            /** @description Informasi spesifik tambahan (misal daftar board yang ditemukan). */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /** @description Laporan komprehensif kesehatan layanan backend. */
        HealthResponse: {
            /**
             * @description Status operasional agregat layanan backend.
             * @example ok
             * @enum {string}
             */
            status: "ok" | "degraded" | "error";
            /**
             * @description Unix timestamp detik pemeriksaan.
             * @example 1791028310
             */
            timestamp: number;
            /**
             * Format: float
             * @description Total waktu aktif proses FastAPI dalam detik.
             * @example 3600.5
             */
            uptime_seconds: number;
            /**
             * Format: float
             * @description Konsumsi memori Resident Set Size (RSS) proses Uvicorn dalam MB (harus < 150 MB).
             * @example 48.2
             */
            memory_rss_mb: number;
            /**
             * @description Versi aplikasi backend office.
             * @example 2.0.0
             */
            version: string;
            /** @description Status kesehatan masing-masing komponen modul pembaca data sumber. */
            readers: {
                kanban: components["schemas"]["ReaderHealth"];
                gateway: components["schemas"]["ReaderHealth"];
                profiles: components["schemas"]["ReaderHealth"];
                host: components["schemas"]["ReaderHealth"];
            };
        };
        /** @description Format standar representasi kesalahan API. */
        ErrorResponse: {
            /**
             * @description Pesan deskripsi kesalahan yang mudah dipahami.
             * @example Autentikasi Founder diperlukan untuk mengakses resource ini
             */
            error: string;
            /**
             * @description Kode klasifikasi error mesin.
             * @example UNAUTHORIZED
             */
            code: string;
            /** @description Detail konteks tambahan atas error jika ada. */
            details?: {
                [key: string]: unknown;
            } | null;
        };
        /**
         * @description Polimorfik payload data yang dikirimkan melalui format Server-Sent Events text/event-stream.
         *     Format transmisi di wire:
         *     ```
         *     event: <event_name>
         *     id: <seq>
         *     data: <JSON_string>
         *     ```
         */
        SSEPayload: components["schemas"]["SSESnapshotEvent"] | components["schemas"]["SSEAgentDeltaEvent"] | components["schemas"]["SSEOfficeFeedEvent"] | components["schemas"]["SSEVitalsEvent"] | components["schemas"]["SSECollectiveEvent"];
        /** @description Event snapshot: Dikirimkan segera saat koneksi baru terbentuk atau saat reconnect gap melebihi batas buffer. */
        SSESnapshotEvent: {
            /**
             * @example snapshot
             * @enum {string}
             */
            event: "snapshot";
            /**
             * @description Sequence ID terakhir.
             * @example 142
             */
            id?: string;
            data: components["schemas"]["WorldSnapshot"];
        };
        /** @description Event agent: Dikirimkan ketika terdapat perubahan status atau aksi pada satu agen. */
        SSEAgentDeltaEvent: {
            /**
             * @example agent
             * @enum {string}
             */
            event: "agent";
            /**
             * @description Sequence ID event pemicu perubahan.
             * @example 143
             */
            id?: string;
            data: components["schemas"]["AgentState"];
        };
        /** @description Event event: Dikirimkan ketika ada peristiwa linimasa baru (task mulai, selesai, terblokir, dll.). */
        SSEOfficeFeedEvent: {
            /**
             * @example event
             * @enum {string}
             */
            event: "event";
            /**
             * @description Sequence ID event.
             * @example 144
             */
            id?: string;
            data: components["schemas"]["OfficeEvent"];
        };
        /** @description Event vitals: Dikirimkan secara periodik (setiap 5 detik) untuk memperbarui indikator sumber daya server. */
        SSEVitalsEvent: {
            /**
             * @example vitals
             * @enum {string}
             */
            event: "vitals";
            data: components["schemas"]["HostVitals"];
        };
        /** @description Event collective: Dikirimkan saat event kolektif dimulai, diperbarui, atau selesai. */
        SSECollectiveEvent: {
            /**
             * @example collective
             * @enum {string}
             */
            event: "collective";
            /** @example 145 */
            id?: string;
            data?: components["schemas"]["CollectiveEventState"] | null;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    getWorldSnapshot: {
        parameters: {
            query?: {
                /** @description Proyeksi data yang diminta (public atau founder). */
                projection?: "public" | "founder";
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Snapshot dunia kantor berhasil diambil. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["WorldSnapshot"];
                };
            };
            /** @description Tidak terautentikasi untuk meminta proyeksi founder. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    streamEvents: {
        parameters: {
            query?: never;
            header?: {
                /** @description Nomor urut sequence (seq) terakhir yang diterima klien untuk resume delta dari ring buffer. */
                "Last-Event-ID"?: string;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Stream event SSE aktif. */
            200: {
                headers: {
                    "Content-Type"?: string;
                    "Cache-Control"?: string;
                    Connection?: string;
                    "X-Accel-Buffering"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "text/event-stream": components["schemas"]["SSEPayload"];
                };
            };
            /** @description Format header Last-Event-ID tidak valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getAgentDetail: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                /** @description Identifier unik profil agen. */
                id: "jarvis" | "daedalus" | "oracle" | "forge" | "prism" | "sentinel" | "muse" | "bastion" | "relay" | "vector" | "nova" | "steward" | "scribe" | "merlin" | "warden" | "rifqi";
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Detail profil agen berhasil ditemukan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["AgentProfileDetail"];
                };
            };
            /** @description Agen dengan ID tersebut tidak ditemukan. */
            404: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    loginFounder: {
        parameters: {
            query?: never;
            header: {
                /** @description Header proteksi CSRF. Nilai harus bernilai "1". */
                "X-Office-Intent": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LoginRequest"];
            };
        };
        responses: {
            /** @description Login berhasil, cookie sesi diterbitkan. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LoginResponse"];
                };
            };
            /** @description Header X-Office-Intent tidak ada atau format payload salah. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Password Founder salah. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Terlalu banyak percobaan login (maks. 5 kali per 15 menit). */
            429: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    logoutFounder: {
        parameters: {
            query?: never;
            header: {
                /** @description Header proteksi CSRF. Nilai harus bernilai "1". */
                "X-Office-Intent": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Logout berhasil, cookie sesi direset. */
            200: {
                headers: {
                    "Set-Cookie"?: string;
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LogoutResponse"];
                };
            };
            /** @description Header X-Office-Intent tidak ada. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Sesi tidak valid atau telah berakhir. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    triggerCollectiveEvent: {
        parameters: {
            query?: never;
            header: {
                /** @description Header proteksi CSRF. Nilai harus bernilai "1". */
                "X-Office-Intent": "1";
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TriggerCollectiveRequest"];
            };
        };
        responses: {
            /** @description Event kolektif berhasil dipicu dan disiarkan. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CollectiveEventState"];
                };
            };
            /** @description Header X-Office-Intent tidak ada atau parameter kind tidak valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Tidak terautentikasi sebagai Founder. */
            401: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Event kolektif lain masih berlangsung aktif. */
            409: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
        };
    };
    getHealthStatus: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Status operasional backend dan reader data. */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
            /** @description Request tidak valid. */
            400: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ErrorResponse"];
                };
            };
            /** @description Layanan mengalami degradasi atau satu atau lebih reader sumber error. */
            503: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HealthResponse"];
                };
            };
        };
    };
}
