import * as THREE from 'three'

export interface Agent3DDef {
  id: string
  name: string
  role: string
  color: string
  emoji: string
  position: THREE.Vector3
  targetPosition: THREE.Vector3
  facing: string
  state: 'idle' | 'walking' | 'working' | 'meeting' | 'swimming' | 'praying'
  speechText?: string
  task?: string
  screenPos?: { x: number; y: number; visible: boolean }
}

export const INITIAL_3D_AGENTS: Agent3DDef[] = [
  {
    id: 'vps-boss',
    name: 'Jarvis',
    role: 'Chief Orchestrator',
    color: '#eab308',
    emoji: '👑',
    position: new THREE.Vector3(9.0, 1.45, -7.5),
    targetPosition: new THREE.Vector3(9.0, 1.45, -7.5),
    facing: 'south',
    state: 'working',
    speechText: 'Lord Commander memantau status seluruh VPS 👑',
    task: 'Governing 14 Sovereign Agents',
  },
  {
    id: 'vps-assistant',
    name: 'vps-assistant',
    role: 'General Utility',
    color: '#a855f7',
    emoji: '⚡',
    position: new THREE.Vector3(11.2, 1.45, -5.2),
    targetPosition: new THREE.Vector3(11.2, 1.45, -5.2),
    facing: 'south-west',
    state: 'idle',
    speechText: 'Nunggu keputusan Rifqi 📋',
    task: 'Operational Task Runner',
  },
  {
    id: 'rifqi',
    name: 'Rifqi Setiawan',
    role: 'Supreme Authority',
    color: '#38bdf8',
    emoji: '💼',
    position: new THREE.Vector3(11.0, -0.1, 6.0),
    targetPosition: new THREE.Vector3(11.0, -0.1, 6.0),
    facing: 'east',
    state: 'swimming',
    speechText: 'Santai di kolam renang rooftop 🏊',
    task: 'Founder & Supreme Authority',
  },
  {
    id: 'senku',
    name: 'Senku',
    role: 'Research Scientist',
    color: '#22c55e',
    emoji: '🧪',
    position: new THREE.Vector3(-11.0, 0.45, 0.0),
    targetPosition: new THREE.Vector3(-11.0, 0.45, 0.0),
    facing: 'north',
    state: 'working',
    speechText: 'Riset 10,000,000% logis dan presisi 🧪',
    task: 'Scientific Systems & Algorithms',
  },
  {
    id: 'paperwright',
    name: 'paperwright',
    role: 'Scientific Scribe',
    color: '#ec4899',
    emoji: '📜',
    position: new THREE.Vector3(-7.2, 0.45, 0.0),
    targetPosition: new THREE.Vector3(-7.2, 0.45, 0.0),
    facing: 'north',
    state: 'working',
    speechText: 'Kompilasi TeX PDF manuscript bersih 📄',
    task: 'LaTeX & Academic Publications',
  },
  {
    id: 'swe-backend',
    name: 'swe-backend',
    role: 'Backend Architect',
    color: '#3b82f6',
    emoji: '💻',
    position: new THREE.Vector3(0.0, 0.45, 1.8),
    targetPosition: new THREE.Vector3(0.0, 0.45, 1.8),
    facing: 'north',
    state: 'working',
    speechText: 'Worktree bersih, FastAPI latency 12ms 🚀',
    task: 'High-Concurrency APIs & DuckDB',
  },
  {
    id: 'swe-frontend',
    name: 'swe-frontend',
    role: 'Frontend Specialist',
    color: '#06b6d4',
    emoji: '🎨',
    position: new THREE.Vector3(-4.0, 0.45, 1.8),
    targetPosition: new THREE.Vector3(-4.0, 0.45, 1.8),
    facing: 'north',
    state: 'working',
    speechText: 'Three.js 60 FPS tanpa visual jitter 🎯',
    task: 'WebGL 3D & Responsive UI',
  },
  {
    id: 'swe-qa',
    name: 'swe-QA',
    role: 'Independent Verifier',
    color: '#10b981',
    emoji: '🛡️',
    position: new THREE.Vector3(0.0, 0.45, 5.3),
    targetPosition: new THREE.Vector3(0.0, 0.45, 5.3),
    facing: 'north',
    state: 'working',
    speechText: 'Semua 31 unit test PASS 100% ✅',
    task: 'Independent QA & Verification',
  },
  {
    id: 'ui-designer',
    name: 'ui-designer',
    role: 'Principal UI/UX',
    color: '#f43f5e',
    emoji: '✨',
    position: new THREE.Vector3(-4.0, 0.45, 5.3),
    targetPosition: new THREE.Vector3(-4.0, 0.45, 5.3),
    facing: 'north',
    state: 'working',
    speechText: 'Anti-AI-slop design system aktif ✨',
    task: 'Aesthetics & Interaction Design',
  },
  {
    id: 'data-engineer',
    name: 'data-engineer',
    role: 'Lakehouse Specialist',
    color: '#f59e0b',
    emoji: '🌊',
    position: new THREE.Vector3(6.0, 0.45, 7.2),
    targetPosition: new THREE.Vector3(6.0, 0.45, 7.2),
    facing: 'south',
    state: 'working',
    speechText: 'Parquet Medallion sync sukses 📊',
    task: 'DuckLake ACID Pipelines',
  },
  {
    id: 'devops-engineer',
    name: 'devops-engineer',
    role: 'Infrastructure SRE',
    color: '#6366f1',
    emoji: '🚀',
    position: new THREE.Vector3(4.0, 0.45, 7.2),
    targetPosition: new THREE.Vector3(4.0, 0.45, 7.2),
    facing: 'south',
    state: 'working',
    speechText: 'Uptime 9 hari, Caddy reverse proxy sehat 🛡️',
    task: 'Systemd & Azure VM Telemetry',
  },
  {
    id: 'tech-mentor',
    name: 'tech-mentor',
    role: 'Architecture Tutor',
    color: '#8b5cf6',
    emoji: '🎓',
    position: new THREE.Vector3(-1.0, 1.45, -6.5),
    targetPosition: new THREE.Vector3(-1.0, 1.45, -6.5),
    facing: 'east',
    state: 'meeting',
    speechText: 'Diskusi arsitektur microservices di ruang kaca 🤝',
    task: 'Interactive Technical Tutoring',
  },
  {
    id: 'chief-architect',
    name: 'chief-architect',
    role: 'Chief Architect',
    color: '#64748b',
    emoji: '🏛️',
    position: new THREE.Vector3(1.2, 1.45, -6.5),
    targetPosition: new THREE.Vector3(1.2, 1.45, -6.5),
    facing: 'west',
    state: 'meeting',
    speechText: 'Review blueprint sistem terdistribusi 📐',
    task: 'Systems Architecture & RFCs',
  },
  {
    id: 'dimas-musholla',
    name: 'Dimas GL-01',
    role: 'Visiting Dev',
    color: '#059669',
    emoji: '🕌',
    position: new THREE.Vector3(-11.0, -0.65, 7.5),
    targetPosition: new THREE.Vector3(-11.0, -0.65, 7.5),
    facing: 'north',
    state: 'praying',
    speechText: 'Allāhu akbar... ٱللَّٰهُ أَكْبَرُ 🤲',
    task: 'Sholat Berjamaah di Musholla',
  },
]
