import type { FacingDirection } from '../../navigation/types';

export interface AgentSpawnDef {
  id: string;
  name: string;
  role: string;
  signatureColor: string;
  defaultSlotId: string;
  fallbackGx: number;
  fallbackGy: number;
  fallbackFacing: FacingDirection;
}

/**
 * Konfigurasi 16 Agen Spesialis + 1 Tamu Generik + 1 Founder
 * Sesuai blueprint spec 03 dan pemetaan slot peta floor1.tmj.
 */
export const AGENT_SPAWN_DEFS: AgentSpawnDef[] = [
  {
    id: 'jarvis',
    name: 'Jarvis',
    role: 'Principal Orchestrator',
    signatureColor: '#1F3A68',
    defaultSlotId: 'slot_z01_desk_jarvis',
    fallbackGx: 4,
    fallbackGy: 3,
    fallbackFacing: 'SE',
  },
  {
    id: 'daedalus',
    name: 'Daedalus',
    role: 'System Architect',
    signatureColor: '#2F6FB3',
    defaultSlotId: 'slot_z03_desk_daedalus',
    fallbackGx: 23,
    fallbackGy: 3,
    fallbackFacing: 'SE',
  },
  {
    id: 'merlin',
    name: 'Merlin',
    role: 'Knowledge Mentor',
    signatureColor: '#B5652B',
    defaultSlotId: 'slot_z04_whiteboard',
    fallbackGx: 31,
    fallbackGy: 2,
    fallbackFacing: 'SW',
  },
  {
    id: 'scribe',
    name: 'Scribe',
    role: 'Documentation & Librarian',
    signatureColor: '#7A4A2E',
    defaultSlotId: 'slot_z05_desk_scribe',
    fallbackGx: 36,
    fallbackGy: 4,
    fallbackFacing: 'SE',
  },
  {
    id: 'oracle',
    name: 'Oracle',
    role: 'Research Scientist',
    signatureColor: '#8A4FBF',
    defaultSlotId: 'slot_z06_desk_oracle',
    fallbackGx: 6,
    fallbackGy: 13,
    fallbackFacing: 'SE',
  },
  {
    id: 'muse',
    name: 'Muse',
    role: 'Design Lead',
    signatureColor: '#E0567A',
    defaultSlotId: 'slot_z07_desk_muse',
    fallbackGx: 10,
    fallbackGy: 13,
    fallbackFacing: 'SE',
  },
  {
    id: 'prism',
    name: 'Prism',
    role: 'Frontend Specialist',
    signatureColor: '#2BB3C0',
    defaultSlotId: 'slot_z08_desk_prism',
    fallbackGx: 17,
    fallbackGy: 12,
    fallbackFacing: 'SE',
  },
  {
    id: 'forge',
    name: 'Forge',
    role: 'Backend Specialist',
    signatureColor: '#D9622B',
    defaultSlotId: 'slot_z08_desk_forge',
    fallbackGx: 17,
    fallbackGy: 14,
    fallbackFacing: 'SE',
  },
  {
    id: 'nova',
    name: 'Nova',
    role: 'Ops & Automation',
    signatureColor: '#F2C230',
    defaultSlotId: 'slot_z08_desk_nova',
    fallbackGx: 17,
    fallbackGy: 16,
    fallbackFacing: 'SE',
  },
  {
    id: 'steward',
    name: 'Steward',
    role: 'Graphics & Engine Lead',
    signatureColor: '#9CC23A',
    defaultSlotId: 'slot_z09_desk_steward',
    fallbackGx: 25,
    fallbackGy: 12,
    fallbackFacing: 'SE',
  },
  {
    id: 'sentinel',
    name: 'Sentinel',
    role: 'QA Lead & Auditor',
    signatureColor: '#D23C3C',
    defaultSlotId: 'slot_z10_desk_sentinel',
    fallbackGx: 29,
    fallbackGy: 12,
    fallbackFacing: 'SE',
  },
  {
    id: 'relay',
    name: 'Relay',
    role: 'Release Officer',
    signatureColor: '#6D5BD0',
    defaultSlotId: 'slot_z11_desk_relay',
    fallbackGx: 33,
    fallbackGy: 12,
    fallbackFacing: 'SE',
  },
  {
    id: 'vector',
    name: 'Vector',
    role: 'Data Engineer',
    signatureColor: '#3FA66B',
    defaultSlotId: 'slot_z12_desk_vector',
    fallbackGx: 37,
    fallbackGy: 13,
    fallbackFacing: 'SE',
  },
  {
    id: 'bastion',
    name: 'Bastion',
    role: 'Security & SOC Officer',
    signatureColor: '#6B7785',
    defaultSlotId: 'slot_z12_desk_bastion',
    fallbackGx: 41,
    fallbackGy: 13,
    fallbackFacing: 'SE',
  },
  {
    id: 'warden',
    name: 'Warden',
    role: 'Operations & Facilities',
    signatureColor: '#8E8E3A',
    defaultSlotId: 'slot_z13_desk_warden',
    fallbackGx: 4,
    fallbackGy: 25,
    fallbackFacing: 'SE',
  },
  {
    id: 'rifqi',
    name: 'Rifqi',
    role: 'Founder & Visionary',
    signatureColor: '#F5F0E1',
    defaultSlotId: 'slot_z14_lounge_1',
    fallbackGx: 14,
    fallbackGy: 28,
    fallbackFacing: 'SE',
  },
  {
    id: 'guest',
    name: 'Tamu',
    role: 'Pengunjung Kantor',
    signatureColor: '#9CA8B8',
    defaultSlotId: 'slot_z08_desk_guest',
    fallbackGx: 17,
    fallbackGy: 18,
    fallbackFacing: 'SE',
  },
];
